[nixpacks]
language = "python"

[phases.setup]
nixPkgs = [
  "ffmpeg",
  "libGL",
  "libGLU",
  "libxext",
  "libxrender",
  "libsm",
  "zlib",
  "glib",
  "libstdcxx5"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
