[nixpacks]
language = "python"

[phases.setup]
nixPkgs = ["ffmpeg", "libGL", "zlib", "glib", "libstdcxx5"]

[phases.install]
cmd = "pip install --upgrade pip && pip install -r requirements.txt"

[start]
cmd = "gunicorn app:app"
